name: Add Git trailers for PRs

on:
  push:
    branches: 
    - main

jobs:
  vmspawn:
    runs-on: [self-hosted, x86_64]
    steps:
      - name: Do vm-spawn
        uses: nubificus/vmspawn@v1
        with:
          kcli_key: ${{ secrets.KCLI_ID_RSA }}
          script: "ls -latr /tmp"

